export enum Categories {
  Accessories = 'Accessories',
  Computer = 'Computer System Accessories',
  Desktop = 'Desktop Computers',
  Flat = 'Flat Screens',
  Graphic = 'Graphic Cards',
  Laptops = 'Laptops',
  Multifunction = 'Multifunction Printers',
  Mice = 'Mice',
  Mousepads = 'Mousepads',
  Keyboards = 'Keyboards',
  Servers = 'Servers',
  Scanners = 'Scanners',
  Software = 'Software',
  Speakers = 'Speakers',
  Smartphones = 'Smartphones and Tablets',
  Tablets = 'Tablets',
  Telecommunications = 'Telecommunications',
  Printers = 'Printers',
  PCs = 'PCs',
}
