export enum Categories {
  Accessories = 'Accessories',
  ComputerSystemAccessories = 'Computer System Accessories',
  DesktopComputers = 'Desktop Computers',
  Flat = 'Flat Screen Monitors',
  FlatScreens = 'Flat Screens',
  FlatScreenTVs = 'Flat Screen TVs',
  FlatScreenMonitors = 'Flat Screen Monitors',
  GraphicCards = 'Graphic Cards',
  Laptops = 'Laptops',
  MultifunctionPrinters = 'Multifunction Printers',
  Mice = 'Mice',
  Mousepads = 'Mousepads',
  Keyboards = 'Keyboards',
  Servers = 'Servers',
  Scanners = 'Scanners',
  Software = 'Software',
  Speakers = 'Speakers',
  SmartphonesAndTablets = 'Smartphones and Tablets',
  Tablets = 'Tablets',
  Telecommunications = 'Telecommunications',
  Printers = 'Printers',
  PCs = 'PCs',
}
